---
version: '3'

services:
  traefik:
    image: traefik:latest
    ports:
      - 80:80
      - 443:443
    networks:
      - traefik-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
      - ./certs/:/certs/
    deploy:
      labels:
        - "traefik.port=8080"
        - "traefik.frontend.rule=Host:dashboard.mytraefik.de"
        - "traefik.backend=traefik-dashboard"

networks:
  traefik-net:
    external: true
