#debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
    address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
    address = ":443"
  [entryPoints.https.tls]
    [[entryPoints.https.tls.certificates]]
      certFile = "/certs/traefik.crt"
      keyFile = "/certs/traefik.key"
  [entryPoints.traefik-dashboard]
    address = ":8080"

[api]
dashboard = true
entryPoint = "traefik-dashboard"

#[web]
#entryPoint = "traefik-dashboard"

#[retry]

[docker]
#endpoint = "unix:///var/run/docker.sock"
domain = "traefik"
watch = true
swarmmode = true
#exposedbydefault = false
