---
version: '3.3'

services:
  whoami:
    image: emilevauge/whoami
    networks:
      - traefik-net
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "Host:${SERVICE_URL}"
        #    env_file: 
        #      - "whoami.default.env"
    environment:
     - SERVICE_URL=${SERVICE_URL}
networks:
  traefik-net:
    external: true
